name: .NET

on: pull_request

jobs:
  build_and_test:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK '5.0.x'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore Callculator.sln
        
      - name: Build
        run: dotnet build Callculator.sln --configuration Release --no-restore
        
      - name: Launch
        run: cd ./Callculator/bin/Release/net5.0 && start Callculator.exe
        
      - name: Test
        run: dotnet test Callculator.sln --configuration Release --no-restore --verbosity Minimal

      - name: Screenshots - Publish
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with: 
          name: ScreenShots
          path: ./Callculator/bin/Release/net5.0/ScreenShots